/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SubEventService } from "../subEvent.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SubEventCreateInput } from "./SubEventCreateInput";
import { SubEvent } from "./SubEvent";
import { SubEventFindManyArgs } from "./SubEventFindManyArgs";
import { SubEventWhereUniqueInput } from "./SubEventWhereUniqueInput";
import { SubEventUpdateInput } from "./SubEventUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SubEventControllerBase {
  constructor(
    protected readonly service: SubEventService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SubEvent })
  @nestAccessControl.UseRoles({
    resource: "SubEvent",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSubEvent(
    @common.Body() data: SubEventCreateInput
  ): Promise<SubEvent> {
    return await this.service.createSubEvent({
      data: {
        ...data,

        event: data.event
          ? {
              connect: data.event,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        endsAt: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        scheduledAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SubEvent] })
  @ApiNestedQuery(SubEventFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SubEvent",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async subEvents(@common.Req() request: Request): Promise<SubEvent[]> {
    const args = plainToClass(SubEventFindManyArgs, request.query);
    return this.service.subEvents({
      ...args,
      select: {
        createdAt: true,
        description: true,
        endsAt: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        scheduledAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SubEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SubEvent",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async subEvent(
    @common.Param() params: SubEventWhereUniqueInput
  ): Promise<SubEvent | null> {
    const result = await this.service.subEvent({
      where: params,
      select: {
        createdAt: true,
        description: true,
        endsAt: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        scheduledAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SubEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SubEvent",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSubEvent(
    @common.Param() params: SubEventWhereUniqueInput,
    @common.Body() data: SubEventUpdateInput
  ): Promise<SubEvent | null> {
    try {
      return await this.service.updateSubEvent({
        where: params,
        data: {
          ...data,

          event: data.event
            ? {
                connect: data.event,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          endsAt: true,

          event: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,
          scheduledAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SubEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SubEvent",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSubEvent(
    @common.Param() params: SubEventWhereUniqueInput
  ): Promise<SubEvent | null> {
    try {
      return await this.service.deleteSubEvent({
        where: params,
        select: {
          createdAt: true,
          description: true,
          endsAt: true,

          event: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,
          scheduledAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
