/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsDate, ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { GuestUpdateManyWithoutEventsInput } from "./GuestUpdateManyWithoutEventsInput";
import { NotificationUpdateManyWithoutEventsInput } from "./NotificationUpdateManyWithoutEventsInput";
import { SubEventUpdateManyWithoutEventsInput } from "./SubEventUpdateManyWithoutEventsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class EventUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endsAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => GuestUpdateManyWithoutEventsInput,
  })
  @ValidateNested()
  @Type(() => GuestUpdateManyWithoutEventsInput)
  @IsOptional()
  @Field(() => GuestUpdateManyWithoutEventsInput, {
    nullable: true,
  })
  guests?: GuestUpdateManyWithoutEventsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => NotificationUpdateManyWithoutEventsInput,
  })
  @ValidateNested()
  @Type(() => NotificationUpdateManyWithoutEventsInput)
  @IsOptional()
  @Field(() => NotificationUpdateManyWithoutEventsInput, {
    nullable: true,
  })
  notifications?: NotificationUpdateManyWithoutEventsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  scheduledAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => SubEventUpdateManyWithoutEventsInput,
  })
  @ValidateNested()
  @Type(() => SubEventUpdateManyWithoutEventsInput)
  @IsOptional()
  @Field(() => SubEventUpdateManyWithoutEventsInput, {
    nullable: true,
  })
  subEvents?: SubEventUpdateManyWithoutEventsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { EventUpdateInput as EventUpdateInput };
