/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Guest } from "./Guest";
import { GuestCountArgs } from "./GuestCountArgs";
import { GuestFindManyArgs } from "./GuestFindManyArgs";
import { GuestFindUniqueArgs } from "./GuestFindUniqueArgs";
import { CreateGuestArgs } from "./CreateGuestArgs";
import { UpdateGuestArgs } from "./UpdateGuestArgs";
import { DeleteGuestArgs } from "./DeleteGuestArgs";
import { NotificationFindManyArgs } from "../../notification/base/NotificationFindManyArgs";
import { Notification } from "../../notification/base/Notification";
import { PhotoFindManyArgs } from "../../photo/base/PhotoFindManyArgs";
import { Photo } from "../../photo/base/Photo";
import { Event } from "../../event/base/Event";
import { GuestService } from "../guest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Guest)
export class GuestResolverBase {
  constructor(
    protected readonly service: GuestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Guest",
    action: "read",
    possession: "any",
  })
  async _guestsMeta(
    @graphql.Args() args: GuestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Guest])
  @nestAccessControl.UseRoles({
    resource: "Guest",
    action: "read",
    possession: "any",
  })
  async guests(@graphql.Args() args: GuestFindManyArgs): Promise<Guest[]> {
    return this.service.guests(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Guest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Guest",
    action: "read",
    possession: "own",
  })
  async guest(
    @graphql.Args() args: GuestFindUniqueArgs
  ): Promise<Guest | null> {
    const result = await this.service.guest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Guest)
  @nestAccessControl.UseRoles({
    resource: "Guest",
    action: "create",
    possession: "any",
  })
  async createGuest(@graphql.Args() args: CreateGuestArgs): Promise<Guest> {
    return await this.service.createGuest({
      ...args,
      data: {
        ...args.data,

        event: args.data.event
          ? {
              connect: args.data.event,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Guest)
  @nestAccessControl.UseRoles({
    resource: "Guest",
    action: "update",
    possession: "any",
  })
  async updateGuest(
    @graphql.Args() args: UpdateGuestArgs
  ): Promise<Guest | null> {
    try {
      return await this.service.updateGuest({
        ...args,
        data: {
          ...args.data,

          event: args.data.event
            ? {
                connect: args.data.event,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Guest)
  @nestAccessControl.UseRoles({
    resource: "Guest",
    action: "delete",
    possession: "any",
  })
  async deleteGuest(
    @graphql.Args() args: DeleteGuestArgs
  ): Promise<Guest | null> {
    try {
      return await this.service.deleteGuest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Notification], { name: "notifications" })
  @nestAccessControl.UseRoles({
    resource: "Notification",
    action: "read",
    possession: "any",
  })
  async findNotifications(
    @graphql.Parent() parent: Guest,
    @graphql.Args() args: NotificationFindManyArgs
  ): Promise<Notification[]> {
    const results = await this.service.findNotifications(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Photo], { name: "photos" })
  @nestAccessControl.UseRoles({
    resource: "Photo",
    action: "read",
    possession: "any",
  })
  async findPhotos(
    @graphql.Parent() parent: Guest,
    @graphql.Args() args: PhotoFindManyArgs
  ): Promise<Photo[]> {
    const results = await this.service.findPhotos(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Event, {
    nullable: true,
    name: "event",
  })
  @nestAccessControl.UseRoles({
    resource: "Event",
    action: "read",
    possession: "any",
  })
  async getEvent(@graphql.Parent() parent: Guest): Promise<Event | null> {
    const result = await this.service.getEvent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
